export const GET_BRANCHES_SUCCESS = "GET_BRANCHES_SUCCESS";
export const GET_SEMESTERS_SUCCESS = "GET_SEMESTERS_SUCCESS";
export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS";
export const GET_APPROVED_RESOURCES_SUCCESS = "GET_APPROVED_RESOURCES_SUCCESS";
export const GET_PENDING_RESOURCES_SUCCESS = "GET_PENDING_RESOURCES_SUCCESS";