// CLUB ACTIONS
export const GET_ALL_CLUBS_REQUEST = "GET_ALL_CLUBS_REQUEST";
export const GET_ALL_CLUBS_SUCCESS = "GET_ALL_CLUBS_SUCCESS";
export const GET_ALL_CLUBS_FAILURE = "GET_ALL_CLUBS_FAILURE";

export const GET_CLUB_BY_ID_REQUEST = "GET_CLUB_BY_ID_REQUEST";
export const GET_CLUB_BY_ID_SUCCESS = "GET_CLUB_BY_ID_SUCCESS";
export const GET_CLUB_BY_ID_FAILURE = "GET_CLUB_BY_ID_FAILURE";

export const CREATE_CLUB_REQUEST = "CREATE_CLUB_REQUEST";
export const CREATE_CLUB_SUCCESS = "CREATE_CLUB_SUCCESS";
export const CREATE_CLUB_FAILURE = "CREATE_CLUB_FAILURE";

export const UPDATE_CLUB_REQUEST = "UPDATE_CLUB_REQUEST";
export const UPDATE_CLUB_SUCCESS = "UPDATE_CLUB_SUCCESS";
export const UPDATE_CLUB_FAILURE = "UPDATE_CLUB_FAILURE";

// EVENT ACTIONS
export const GET_CLUB_EVENTS_REQUEST = "GET_CLUB_EVENTS_REQUEST";
export const GET_CLUB_EVENTS_SUCCESS = "GET_CLUB_EVENTS_SUCCESS";
export const GET_CLUB_EVENTS_FAILURE = "GET_CLUB_EVENTS_FAILURE";

export const CREATE_CLUB_EVENT_REQUEST = "CREATE_CLUB_EVENT_REQUEST";
export const CREATE_CLUB_EVENT_SUCCESS = "CREATE_CLUB_EVENT_SUCCESS";
export const CREATE_CLUB_EVENT_FAILURE = "CREATE_CLUB_EVENT_FAILURE";