export const CREATE_MESSAGE_REQUEST="CREATE_MESSAGE_REQUEST";
export const CREATE_MESSAGE_SUCCESS="CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAILUER="CREATE_MESSAGE_FAILUER";

export const CREATE_CHAT_REQUEST="CREATE_CHAT_REQUEST";
export const CREATE_CHAT_SUCCESS="CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAILUER="CREATE_CHAT_FAILUER";

export const GET_ALL_CHATS_REQUEST="GET_ALL_CHATS_REQUEST";
export const GET_ALL_CHATS_SUCCESS="GET_ALL_CHATS_SUCCESS";
export const GET_ALL_CHATS_FAILUER="GET_ALL_CHATS_FAILUER";

export const MOVE_CHAT_TO_TOP="MOVE_CHAT_TO_TOP";